name: Ruby

on:
  - push
  - pull_request

jobs:
  license_checks:
    name: License checks
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true # bundle installs and caches dependencies
      - name: Run license checks
        run: |
          bundle exec license_finder || (cat <<-END && exit 1)

            You seem to be introducing a new license into our stack, please reach out to
            #licenses-tech-stack on slack to get guidance on the topic.
          END

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0, 3.1, 3.2, 3.3, head, truffleruby-head]
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # bundle installs and caches dependencies
      - name: Run tests
        run: bundle exec rake --trace

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs:
      - test
      - license_checks
    if: always()

    steps:
      - name: Successful builds?
        run: |
          if ${{ needs.test.result != 'success' }}; then exit 1; fi
          if ${{ needs.license_checks.result != 'success' }}; then exit 1; fi
